### PR TITLE
Removing origin header to fix an issue when using an headless chrome instance

### PR DESCRIPTION
**Pull request by vrobert78**
The goal is to fix issue #15 . 
Removing the header makes it works.

### CODE REVIEW

**Comment by enricodias** [comment]
I've never had a problem related to this issue and I'm not sure about the implications of removing the origin verification. Regardless of that, just ignoring an argument doesn't seem to be a good solution, especially in a protected method that shouldn't be accessible outside this package directly anyways.

Either the whole argument gets removed, which is not a good idea since that may break things, or it becomes optional.

**Comment by GrahamCampbell** [comment]
Yeh, I think this header is important for security.

**Comment by vrobert78** [comment]
We have this issue in a containerization context. We're running on a PaaS. This PaaS provides a Chrome Headless service. 
There is no means to configure the origin that we would like to authorize in this service.

If we use the code as it is, Chrome answers:
```
Expected handshake response status code 101, but received 403. Rejected an incoming WebSocket connection from the http://127.0.0.1/ origin. Use the command line flag --remote-allow-origins=http://127.0.0.1/ to allow connections from this origin or --remote-allow-origins=* to allow all origins.
```
Removing this origin header is the only way to make it work in our context.

Perhaps there is a way to make it an option rather than dropping it completely.

**Comment by GrahamCampbell** [comment]
You can work around this by passing null as the origin header. Set it in the headers param to `getRequestHandshake`.

**Comment by vrobert78** [comment]
I like the idea.

Does it mean we should patch  https://github.com/chrome-php/chrome/blob/2b7cb13e618602d13bdede20b6b7ae478f3f6eaa/src/Communication/Connection.php#L109C75-L109C94 to authorize the user to pass an option and set its own origin value instead of "http://127.0.0.1" ?

**Comment by GrahamCampbell** [comment]
No, it doesn't matter what the origin is there. The key is that this line unsets the header if you set the headers correctly. https://github.com/chrome-php/wrench/blob/2cf557fad6b5fe6a1a01e18ad67c48eb889d216a/src/Client.php#L236

**Comment by GrahamCampbell** [comment]
This is not such a pretty solution, but I'm not sure I want to bake in bad security into the library.

**Comment by vrobert78** [comment]
@GrahamCampbell the line you mentioned 
https://github.com/chrome-php/wrench/blob/2cf557fad6b5fe6a1a01e18ad67c48eb889d216a/src/Client.php#L236

needs to have property `headers` to be set.

1: for that it would need to call the method `addRequestHeader` which doesn't accept `null` as there is a string type enforced.
2: I'm not the one calling the Wrench methods directly. I'm using the `chrome-php/chrome` library which does the required sub-calls.
3: `chrome-php/chrome` creates a Wrench client with an arbitrary `http://127.0.0.1` for the origin parameter: 

https://github.com/chrome-php/chrome/blob/2b7cb13e618602d13bdede20b6b7ae478f3f6eaa/src/Communication/Connection.php#L109

I don't see a good way to solve this issue, except to remove this Origin header by including my own composer patch.

**Comment by vrobert78** [comment]
FYI, we've found a workaround by starting chrome with  `--remote-allow-origins=*`, in that case it'll authorize any incoming origin header.
See: https://github.com/vrobert78/chrome-php-test for a docker-based example.

**Pull request closed without merging**
